export const SATISFACTION_URL = "https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=AJuOCND_jkW_oaz0xZbTy8TzTqmi5WJLoY3p_yPqEVlUNUVNWU9XTDJUOTBQSEVLTlM3RVZQSzc1MSQlQCN0PWcu&origin=QRCode";
export const QUOTATION_URL = "https://www.aglgroup.com/en/Quotation-form";

export const MINING_STAGES = [
  { id: "exploration", fr: "Exploration", en: "Exploration", icon: "Compass", title: "Ouvrir la voie au projet", titleEn: "Open the way for the project", text: "Études de faisabilité, accès aux sites isolés et acheminement des équipes et équipements d’exploration.", textEn: "Feasibility studies, remote-site access and delivery of exploration teams and equipment.", capabilities: ["Route surveys", "Air & ocean freight", "Personnel management"], image: "image25" },
  { id: "construction", fr: "Construction", en: "Construction", icon: "Crane", title: "Synchroniser les équipements", titleEn: "Synchronise equipment delivery", text: "Coordonner les origines multiples, les cargaisons hors gabarit, les opérations de levage et les formalités douanières.", textEn: "Coordinate multiple origins, oversized cargo, heavy lifts and customs procedures.", capabilities: ["Heavy lift engineering", "OOG transport", "Customs & trade compliance", "Project coordination"], image: "image19" },
  { id: "production", fr: "Production", en: "Production", icon: "Factory", title: "Assurer la continuité du site", titleEn: "Keep the site operating", text: "Organiser les stocks, les approvisionnements, les laydown yards et la logistique sur site pour soutenir les opérations.", textEn: "Manage stock, replenishment, laydown yards and onsite logistics to support operations.", capabilities: ["Industrial warehousing", "Stockpile management", "Inventory management", "Onsite deployment"], image: "image15" },
  { id: "export", fr: "Exportation", en: "Export", icon: "Ship", title: "Connecter la mine au marché", titleEn: "Connect the mine to the market", text: "Combiner les modes de transport, coordonner le passage portuaire et suivre les flux jusqu’à la connexion maritime.", textEn: "Combine transport modes, coordinate port handling and track flows to the maritime connection.", capabilities: ["Multimodal transport", "Freight forwarding", "Cross-border transport", "Track & trace / EDI / API"], image: "image26" },
  { id: "closure", fr: "Fermeture", en: "Closure", icon: "Leaf", title: "Accompagner la fin du cycle", titleEn: "Support the end of the lifecycle", text: "Planifier la démobilisation des moyens et les flux de retour, avec une coordination attentive aux exigences locales et QHSE.", textEn: "Plan equipment demobilisation and return flows, with attention to local and QHSE requirements.", capabilities: ["Demobilisation", "Reverse logistics", "Local coordination"], image: "image24" },
];

export const TOKADEH = {
  title: "Tokadeh Phase II — Liberia",
  context: "Extension d’une mine de fer dans les monts Nimba : construction d’un concentrateur à Tokadeh et d’un nouveau chargeur de navires au port de Buchanan.",
  challenges: ["Déchargement de 34 navires affrétés", "Opérations au port de Buchanan", "E-houses, locomotives, wagons, tambours miniers et structures métalliques hors gabarit", "Trajet rural complexe et escorte QHSE"],
  solutions: ["Open yard dédié à proximité de la concession", "Grues, chariots, nacelles, reach stackers et moyens spécialisés", "Équipe AGL dédiée au pilotage et à la coordination", "Interventions à Tokadeh, Buchanan et sur le pont de la Saint John’s River"],
  source: "Présentation Mining fournie pour le stand AGL × SIREXE",
};

export const KNOWLEDGE_FACTS = `AGL accompagne les EPC, exploitants miniers, OEM et négociants de minerais sur le cycle minier, de la pré-faisabilité à la fermeture. Expertises : freight forwarding, air/ocean freight, affrètement, transport terrestre, heavy lift engineering, cross-border, douane/exonération/trade compliance, track & trace / EDI / API, entrepôts sous douane ou non, laydown yards, stockpile et inventory management, OOG, études de routes/faisabilité, conception 3D AutoCAD, method statements, risk assessment, coordination sur site. Tokadeh Phase II Liberia : concentrateur à la mine, chargeur au port Buchanan, 34 navires affrétés déchargés, OOG (e-houses, locomotives, wagons, tambours, structures, logements), escorte QHSE, zones rurales. Solutions : open yard dédié, flotte et moyens spécialisés, équipe dédiée, opérations Tokadeh/Buchanan/pont Saint John’s River. Local content : plus de 98 % de collaborateurs nationaux selon la présentation Mining fournie. Ne pas extrapoler ces capacités à un pays sans source locale.`;
