import type { Model3DKind, PartShape } from "./actions";

export type V3 = [number, number, number];
export type Finish = "paint" | "metal" | "rubber" | "glass" | "wood" | "concrete";
export interface ModelMesh { shape: PartShape | "tube" | "torus" | "hull" | "ellipsoid"; size: V3; pos: V3; rot?: V3; color?: string; finish?: Finish; bevel?: number }
export interface PartDef { name: string; explanation: string; color: string; finish?: Finish; explode: V3; meshes: ModelMesh[] }

// ——— Constructeurs de géométrie ———
const box = (size: V3, pos: V3, color?: string, finish?: Finish): ModelMesh => ({ shape: "box", size, pos, color, finish });
const cyl = (r: number, h: number, pos: V3, rot?: V3, color?: string, finish?: Finish): ModelMesh => ({ shape: "cylinder", size: [r, h, r], pos, rot, color, finish });
const wheel = (pos: V3, r = 0.5, w = 0.4): ModelMesh => cyl(r, w, pos, [Math.PI / 2, 0, 0], "#22272f", "rubber");
const wheelRow = (xs: number[], z: number, r = 0.5, w = 0.4, y?: number) => xs.flatMap(x => [wheel([x, y ?? r, -z], r, w), wheel([x, y ?? r, z], r, w)]);
const STACK = ["#b23a2a", "#1f5fa8", "#d9a400", "#2e7d5b", "#e8e8e8", "#7a3fa0"];
const NAVY = "#2a5196", GOLD = "#EED58E";
const range = (n: number, f: (i: number) => number) => Array.from({ length: n }, (_, i) => f(i));
const strap = (x: number, z: number, tilt: number): ModelMesh => ({ shape: "box", size: [0.08, 2.1, 0.08], pos: [x, 2.1, z], rot: [tilt, 0, 0] });

// Tracteur routier 6×6 (cabine, capot, châssis, roues), orienté vers +x.
const tractor = (x: number): ModelMesh[] => [box([2.4, 2.7, 2.5], [x + 1.4, 2.25, 0], "#f2f2f2", "paint"), box([1.4, 0.5, 2.3], [x + 2.8, 1.1, 0], "#e8e8e8", "paint"), box([4.6, 0.4, 1.1], [x, 0.95, 0], "#4a5260", "metal"), ...wheelRow([x + 2, x - 0.4, x - 1.6], 1.1)];
// Remorque hydraulique modulaire : plateau + lignes d’essieux pendulaires.
const modular = (x0: number, lines: number, width = 3): ModelMesh[] => [box([lines * 1.5 + 0.6, 0.45, width], [x0 + lines * 0.75, 1.05, 0], "#4b5566", "metal")];
const modularWheels = (x0: number, lines: number, width = 3): ModelMesh[] => range(lines, i => x0 + 0.75 + i * 1.5).flatMap(x => [-width / 2 + 0.35, -width / 2 + 0.75, width / 2 - 0.75, width / 2 - 0.35].map(z => wheel([x, 0.42, z], 0.42, 0.3)));

// ——— Objets modélisés pièce par pièce ; « explode » = direction de décomposition ———
export const PRESETS: Record<Exclude<Model3DKind, "custom">, PartDef[]> = {
  container: [
    { name: "Plancher", explanation: "Plancher en bois dur posé sur des traverses en acier : il répartit la charge utile, jusqu’à environ 28 tonnes pour un 20 pieds.", color: "#6b4f2a", explode: [0, -1.4, 0], meshes: [box([6, 0.16, 2.4], [0, 0.08, 0])] },
    { name: "Marchandise", explanation: "Marchandise palettisée et arrimée : un bon calage évite les déplacements de charge pendant le transport maritime.", color: GOLD, explode: [0, 0.6, 0], meshes: [-1.9, 0, 1.9].map(x => box([1.5, 1.3, 1.1], [x, 0.81, 0])) },
    { name: "Parois latérales", explanation: "Parois en acier ondulé Corten : elles apportent la rigidité qui permet d’empiler les conteneurs sur plusieurs hauteurs.", color: "#b23a2a", finish: "paint", explode: [0, 0, 1.8], meshes: [box([6, 2.4, 0.06], [0, 1.36, -1.2]), box([6, 2.4, 0.06], [0, 1.36, 1.2])] },
    { name: "Toit", explanation: "Toit en tôle d’acier étanche, protégeant la marchandise des intempéries et des embruns.", color: "#9c3022", finish: "paint", explode: [0, 1.8, 0], meshes: [box([6, 0.08, 2.46], [0, 2.6, 0])] },
    { name: "Face avant", explanation: "Face avant fermée et renforcée, côté opposé aux portes.", color: "#a8352a", finish: "paint", explode: [-1.8, 0, 0], meshes: [box([0.06, 2.4, 2.4], [-3, 1.36, 0])] },
    { name: "Portes et scellés", explanation: "Portes arrière à barres de verrouillage : le scellé posé après empotage garantit l’intégrité du chargement jusqu’au dédouanement.", color: "#c2442f", finish: "paint", explode: [2, 0, 0], meshes: [box([0.06, 2.4, 1.18], [3, 1.36, -0.6]), box([0.06, 2.4, 1.18], [3, 1.36, 0.6])] },
    { name: "Pièces de coin", explanation: "Pièces de coin normalisées ISO : les portiques, cavaliers et verrous tournants s’y accrochent pour lever et arrimer le conteneur.", color: GOLD, finish: "metal", explode: [0, -0.6, 0], meshes: [[-2.95, -1.15], [-2.95, 1.15], [2.95, -1.15], [2.95, 1.15]].flatMap(([x, z]) => [box([0.18, 0.14, 0.16], [x, 0.07, z]), box([0.18, 0.14, 0.16], [x, 2.66, z])]) },
  ],
  truck: [
    { name: "Cabine du tracteur", explanation: "Cabine du tracteur routier : le chauffeur y suit l’itinéraire validé par l’étude de route et reste en contact avec l’escorte.", color: "#f2f2f2", finish: "paint", explode: [2.6, 1, 0], meshes: [box([2.2, 2.6, 2.5], [6.6, 2.1, 0])] },
    { name: "Châssis tracteur", explanation: "Châssis du tracteur, dimensionné pour la puissance de traction nécessaire aux convois lourds.", color: "#4a5260", finish: "metal", explode: [1.6, -1.2, 0], meshes: [box([4.4, 0.35, 1], [5.4, 0.95, 0])] },
    { name: "Sellette d’attelage", explanation: "Sellette d’attelage : le point de liaison entre le tracteur et la remorque, qui transmet une partie du poids.", color: GOLD, finish: "metal", explode: [0, 1.6, 0], meshes: [cyl(0.55, 0.16, [4.4, 1.2, 0])] },
    { name: "Remorque surbaissée", explanation: "Remorque surbaissée : son plateau bas abaisse le centre de gravité et libère la hauteur sous les ponts et les lignes.", color: "#3b4250", finish: "metal", explode: [-1.2, -1.2, 0], meshes: [box([11, 0.35, 2.6], [-2.2, 0.95, 0]), box([1.6, 0.6, 2.4], [3.6, 1.25, 0])] },
    { name: "Essieux et roues", explanation: "Essieux multiples : ils répartissent la charge pour respecter le poids autorisé par essieu et préserver la chaussée.", color: "#151a22", finish: "rubber", explode: [0, -1.8, 0], meshes: wheelRow([7.2, 5.2, 4.2, -4, -5.2, -6.4, -7.6], 1.1) },
    { name: "Équipement minier", explanation: "La charge exceptionnelle : ici un équipement minier. Son gabarit et sa masse déterminent l’itinéraire, l’escorte et les autorisations.", color: "#d9a400", finish: "paint", explode: [0, 2.6, 0], meshes: [box([6, 2.6, 2.6], [-2.4, 2.45, 0]), cyl(0.9, 2.62, [-2.4, 3.9, 0], [Math.PI / 2, 0, 0], "#b88a00")] },
  ],
  crane: [
    { name: "Jambes côté mer", explanation: "Jambes côté mer : elles roulent sur des rails le long du quai pour positionner le portique face à chaque baie du navire.", color: "#2f6db5", finish: "paint", explode: [2.5, 0, 0], meshes: [box([0.6, 14, 0.6], [4, 7, -5]), box([0.6, 14, 0.6], [4, 7, 5])] },
    { name: "Jambes côté terre", explanation: "Jambes côté terre, sous lesquelles circulent les camions et cavaliers qui évacuent les conteneurs.", color: "#2f6db5", finish: "paint", explode: [-2.5, 0, 0], meshes: [box([0.6, 14, 0.6], [-6, 7, -5]), box([0.6, 14, 0.6], [-6, 7, 5])] },
    { name: "Portique", explanation: "Poutres du portique : la structure qui relie les jambes et porte la flèche.", color: "#3a7cc8", finish: "paint", explode: [0, 1.8, 0], meshes: [box([10.6, 0.8, 0.8], [-1, 14.2, -5]), box([10.6, 0.8, 0.8], [-1, 14.2, 5]), box([0.8, 0.8, 10.8], [4, 14.2, 0]), box([0.8, 0.8, 10.8], [-6, 14.2, 0])] },
    { name: "Flèche", explanation: "Flèche : elle s’avance au-dessus du navire pour atteindre les rangées de conteneurs les plus éloignées du quai.", color: "#4a8ad6", finish: "paint", explode: [3, 3, 0], meshes: [box([30, 1, 1.2], [9, 15.4, 0])] },
    { name: "Chariot", explanation: "Chariot : il se déplace le long de la flèche et porte le système de levage.", color: GOLD, finish: "metal", explode: [0, 2.6, 2.4], meshes: [box([2, 1, 2], [14, 14.4, 0])] },
    { name: "Cabine du grutier", explanation: "Cabine du grutier, suspendue sous le chariot pour une vue directe sur le conteneur pendant la manœuvre.", color: "#f2f2f2", finish: "glass", explode: [0, -2, -3.4], meshes: [box([1.8, 1.6, 1.8], [11.8, 13, 0])] },
    { name: "Spreader", explanation: "Spreader (palonnier) : il se verrouille sur les quatre pièces de coin du conteneur grâce à des verrous tournants.", color: GOLD, finish: "metal", explode: [0, -1.4, 3.4], meshes: [box([6.2, 0.4, 2.5], [14, 10.6, 0]), cyl(0.04, 3.6, [14, 12.5, -0.8], undefined, "#cfd6e0"), cyl(0.04, 3.6, [14, 12.5, 0.8], undefined, "#cfd6e0")] },
    { name: "Conteneur levé", explanation: "Le conteneur en cours de levée : un portique moderne enchaîne plusieurs dizaines de mouvements par heure.", color: "#b23a2a", finish: "paint", explode: [0, -3.2, 0], meshes: [box([6, 2.6, 2.4], [14, 9.1, 0])] },
  ],
  ship: [
    { name: "Coque", explanation: "Coque du porte-conteneurs : ses ballasts règlent l’assiette et la stabilité selon le chargement.", color: NAVY, finish: "paint", explode: [0, -3.4, 0], meshes: [box([34, 5, 8], [-1, 2.5, 0]), { shape: "cone", size: [4, 6, 4], pos: [19, 2.5, 0], rot: [0, 0, -Math.PI / 2] }] },
    { name: "Baies de conteneurs", explanation: "Baies de conteneurs : le plan de chargement place les plus lourds en bas et respecte l’ordre des escales de déchargement.", color: "#b23a2a", finish: "paint", explode: [0, 4.4, 0], meshes: range(7, b => b).flatMap(b => [0, 1].flatMap(t => [-2.5, 0, 2.5].map((z, k) => box([3.6, 2.4, 2.3], [-8 + b * 4, 6.3 + t * 2.5, z], STACK[(b + t * 2 + k) % STACK.length])))) },
    { name: "Château et passerelle", explanation: "Château : il abrite la passerelle de navigation et les logements de l’équipage.", color: "#eef1f5", finish: "paint", explode: [-4.4, 3, 0], meshes: [box([5, 8, 7], [-14, 9, 0])] },
    { name: "Cheminée", explanation: "Cheminée : évacuation des gaz du moteur principal, aujourd’hui équipée de systèmes de traitement des émissions.", color: "#b23a2a", finish: "paint", explode: [-2.4, 5, 0], meshes: [cyl(1, 3, [-15.5, 14.5, 0])] },
    { name: "Hélice", explanation: "Hélice : entraînée par le moteur principal, elle propulse le navire ; sa vitesse est optimisée pour la consommation.", color: GOLD, finish: "metal", explode: [-4.4, -1.2, 0], meshes: [cyl(1.6, 0.4, [-19, 1.6, 0], [0, 0, Math.PI / 2])] },
    { name: "Gouvernail", explanation: "Gouvernail : il oriente le navire, notamment lors des manœuvres d’accostage assistées par les remorqueurs.", color: "#3b4250", finish: "metal", explode: [-5.6, 0, 0], meshes: [box([0.3, 3, 1.6], [-19.9, 2.2, 0])] },
  ],
  wagon: [
    { name: "Bogies", explanation: "Bogies : chariots pivotants qui portent le wagon et lui permettent de suivre les courbes de la voie.", color: "#4a5260", finish: "metal", explode: [0, -1.5, 0], meshes: [box([2.6, 0.6, 2], [-5, 0.95, 0]), box([2.6, 0.6, 2], [5, 0.95, 0])] },
    { name: "Essieux montés", explanation: "Essieux montés : la charge par essieu admise par la voie fixe le tonnage que chaque wagon peut transporter.", color: "#151a22", finish: "metal", explode: [0, -2.6, 0], meshes: wheelRow([-5.9, -4.1, 4.1, 5.9], 0.75, 0.45, 0.2) },
    { name: "Plateau porte-conteneurs", explanation: "Plateau du wagon porte-conteneurs : le rail massifie les volumes sur les longues distances, avec des ruptures de charge aux terminaux.", color: "#5a3d2b", explode: [0, 0.6, 0], meshes: [box([14, 0.4, 2.6], [0, 1.5, 0])] },
    { name: "Verrous tournants", explanation: "Verrous tournants : ils fixent les conteneurs au plateau par leurs pièces de coin.", color: GOLD, finish: "metal", explode: [0, 1.4, 0], meshes: [-6.1, -0.1, 0.1, 6.1].flatMap(x => [box([0.2, 0.12, 0.2], [x, 1.76, -1.1]), box([0.2, 0.12, 0.2], [x, 1.76, 1.1])]) },
    { name: "Conteneurs", explanation: "Deux conteneurs 20 pieds chargés : ils passeront du rail au navire ou au camion sans manutention de la marchandise.", color: "#1f5fa8", finish: "paint", explode: [0, 2.6, 0], meshes: [box([6, 2.6, 2.4], [-3.1, 3.1, 0], "#1f5fa8"), box([6, 2.6, 2.4], [3.1, 3.1, 0], "#b23a2a")] },
    { name: "Attelages", explanation: "Attelages : ils relient les wagons entre eux pour former le train.", color: "#8a8f99", finish: "metal", explode: [1.6, 0, 0], meshes: [box([0.6, 0.3, 0.3], [-7.3, 1.3, 0]), box([0.6, 0.3, 0.3], [7.3, 1.3, 0])] },
  ],
  locomotive: [
    { name: "Cabine de conduite", explanation: "Cabine de conduite : commandes informatisées et diagnostic embarqué, comme sur les locomotives GL30 mises en service par Sitarail en décembre 2025.", color: NAVY, finish: "paint", explode: [3.4, 1.2, 0], meshes: [box([3, 3.2, 2.9], [7.3, 3.2, 0]), box([0.08, 1, 2.3], [8.82, 3.9, 0], "#9fc3ea", "glass")] },
    { name: "Capot moteur", explanation: "Capot : il protège la motorisation et s’ouvre pour la maintenance ; le liseré doré rappelle la charte Africa Global Logistics.", color: NAVY, finish: "paint", explode: [0, 4.8, 0], meshes: [box([12.6, 2.4, 2.6], [-0.6, 3.05, 0]), box([12.62, 0.18, 2.62], [-0.6, 2.4, 0], GOLD, "metal")] },
    { name: "Moteur diesel", explanation: "Moteur diesel d’environ 3 000 chevaux : il entraîne l’alternateur, qui produit l’électricité de traction.", color: "#5b6470", finish: "metal", explode: [0, 3, 2.4], meshes: [box([5, 1.6, 1.5], [1.4, 2.7, 0]), ...range(6, i => -0.6 + i * 0.8).map(x => cyl(0.22, 0.5, [x, 3.7, 0], undefined, "#7a8494", "metal"))] },
    { name: "Alternateur principal", explanation: "Alternateur principal : il convertit l’énergie du moteur en courant pour les moteurs de traction — d’où le nom diesel-électrique.", color: GOLD, finish: "metal", explode: [0, 3, -2.6], meshes: [cyl(0.8, 1.4, [-2.2, 2.7, 0], [0, 0, Math.PI / 2])] },
    { name: "Radiateurs", explanation: "Radiateurs et ventilateurs : ils évacuent la chaleur du moteur, essentiel sous climat tropical.", color: "#8a96a6", finish: "metal", explode: [-2.8, 2.6, 0], meshes: [box([3, 1.2, 2.3], [-5.4, 3.7, 0]), cyl(0.5, 0.2, [-4.6, 4.4, 0], undefined, "#4a5260"), cyl(0.5, 0.2, [-6.2, 4.4, 0], undefined, "#4a5260")] },
    { name: "Châssis", explanation: "Châssis porteur : il transmet l’effort de traction aux attelages ; une GL30 peut remorquer de l’ordre de 1 500 tonnes brutes.", color: "#4a5260", finish: "metal", explode: [0, 0.6, 0], meshes: [box([17.4, 0.45, 2.9], [0.4, 1.75, 0]), box([0.5, 0.4, 0.5], [9.3, 1.6, 0], GOLD, "metal"), box([0.5, 0.4, 0.5], [-8.5, 1.6, 0], GOLD, "metal")] },
    { name: "Réservoir de carburant", explanation: "Réservoir de carburant suspendu sous le châssis, pour l’autonomie sur le corridor Abidjan – Ouagadougou.", color: "#3b4250", finish: "metal", explode: [0, -1.4, 2.6], meshes: [box([6, 0.9, 2.1], [0.4, 1.05, 0])] },
    { name: "Bogies et moteurs de traction", explanation: "Bogies à trois essieux : chaque essieu porte un moteur électrique de traction qui fait avancer la locomotive.", color: "#3e4654", finish: "metal", explode: [0, -2.4, 0], meshes: [box([3.8, 0.6, 2.4], [5.8, 0.95, 0]), box([3.8, 0.6, 2.4], [-5, 0.95, 0]), ...[4.6, 5.8, 7, -6.2, -5, -3.8].flatMap(x => [wheel([x, 0.5, -0.8], 0.5, 0.2), wheel([x, 0.5, 0.8], 0.5, 0.2), cyl(0.32, 1, [x, 0.5, 0], [Math.PI / 2, 0, 0], GOLD, "metal")])] },
  ],
  locomotive_convoy: [
    { name: "Grue mobile 400 t — porteur", explanation: "Grue automotrice de 400 tonnes : son porteur se cale sur stabilisateurs pour lever la locomotive au port.", color: "#e3b500", finish: "paint", explode: [0, -1.2, 4.4], meshes: [box([10, 1.2, 3], [-14, 1.5, 0]), ...wheelRow([-17.5, -16, -14.5, -12, -10.5], 1.4, 0.6, 0.5), box([6, 0.3, 0.3], [-14, 0.8, 0], "#4a5260", "metal")] },
    { name: "Flèche télescopique", explanation: "Flèche télescopique : sa longueur et son angle déterminent la charge levable ; le plan de levage est calculé avant l’opération.", color: "#f2c200", finish: "paint", explode: [0, 4, 3], meshes: [box([3.4, 2.2, 2.8], [-14, 3.2, 0]), { shape: "box", size: [22, 1.1, 1.1], pos: [-6.2, 10.4, 0], rot: [0, 0, 0.62] }, cyl(0.05, 6, [2, 13.2, 0], undefined, "#cfd6e0")] },
    { name: "Contrepoids", explanation: "Contrepoids : il équilibre la charge levée et garantit la stabilité de la grue.", color: "#3b4250", finish: "metal", explode: [-3.4, 1, 0], meshes: [box([2.6, 1.8, 2.8], [-17.6, 3.2, 0])] },
    { name: "Locomotive", explanation: "Une des cinq locomotives (332,28 t au total) destinées à la pose des voies de la ligne 1 du métro d’Abidjan, pour Colas Rail.", color: NAVY, finish: "paint", explode: [0, 3.6, 0], meshes: [box([11, 2.6, 2.7], [4, 3.25, 0]), box([2.6, 3.3, 2.8], [10.4, 3.6, 0]), box([11.04, 0.2, 2.74], [4, 2.5, 0], GOLD, "metal")] },
    { name: "Arrimage", explanation: "Arrimage par chaînes et calage : la charge ne doit pas bouger au freinage, en virage ni sur les dévers.", color: "#cfd6e0", finish: "metal", explode: [0, 1.8, 2.2], meshes: [-0.5, 3, 6.5, 9.5].flatMap(x => [strap(x, -1.6, 0.5), strap(x, 1.6, -0.5)]) },
    { name: "Remorque hydraulique modulaire", explanation: "Remorques hydrauliques modulaires Nicolas : leur suspension hydraulique répartit la charge et maintient le plateau de niveau.", color: "#4b5566", finish: "metal", explode: [0, -0.4, 0], meshes: modular(-1.5, 10) },
    { name: "Lignes d’essieux pendulaires", explanation: "Lignes d’essieux pendulaires : nombreuses roues pour répartir la masse sur la chaussée, et essieux directeurs pour tourner.", color: "#22272f", finish: "rubber", explode: [0, -2.2, 0], meshes: modularWheels(-1.5, 10) },
    { name: "Tracteur 6×6", explanation: "Tracteur spécialisé 6×6 : la traction des convois lourds, sous escorte et en coordination avec les autorités.", color: "#f2f2f2", finish: "paint", explode: [3.8, 0.4, 0], meshes: tractor(16) },
  ],
  xmas_tree: [
    { name: "Arbre de production (Xmas-tree)", explanation: "Arbre de production sous-marin : l’assemblage de vannes posé sur la tête de puits pour contrôler le débit d’hydrocarbures. Deux unités de 70 t chacune ont été reçues pour la phase 2 du projet Baleine.", color: GOLD, finish: "metal", explode: [0, 3.4, 0], meshes: [box([2.2, 2.4, 2.2], [0, 4.6, 0]), cyl(0.5, 1.4, [0, 6.5, 0], undefined, "#d4c08a", "metal")] },
    { name: "Cadre de protection", explanation: "Cadre de protection : il supporte l’arbre et le protège pendant le transport, l’installation et l’exploitation en mer.", color: "#f2a900", finish: "paint", explode: [0, 1.6, 3.4], meshes: [...[[-1.8, -1.8], [-1.8, 1.8], [1.8, -1.8], [1.8, 1.8]].map(([x, z]) => box([0.25, 4.6, 0.25], [x, 4.1, z])), box([3.85, 0.25, 0.25], [0, 6.3, -1.8]), box([3.85, 0.25, 0.25], [0, 6.3, 1.8]), box([0.25, 0.25, 3.85], [-1.8, 6.3, 0]), box([0.25, 0.25, 3.85], [1.8, 6.3, 0])] },
    { name: "Connecteur de tête de puits", explanation: "Connecteur de tête de puits : il verrouille l’arbre sur le puits au fond de la mer.", color: "#8a96a6", finish: "metal", explode: [0, -1.4, 0], meshes: [cyl(1.1, 1.2, [0, 2.4, 0])] },
    { name: "Panneau ROV", explanation: "Panneau ROV : interface manœuvrée par un robot sous-marin pour actionner les vannes à grande profondeur.", color: "#1f5fa8", finish: "paint", explode: [3.4, 0.8, 0], meshes: [box([0.2, 1.4, 1.8], [1.95, 4.4, 0])] },
    { name: "Raccord de conduite", explanation: "Raccord de conduite : il relie l’arbre aux lignes de production vers l’installation de surface.", color: "#b0b8c4", finish: "metal", explode: [-3.4, 0.6, 0], meshes: [cyl(0.32, 2.4, [-2.4, 4.2, 0], [0, 0, Math.PI / 2])] },
    { name: "Touret de câble sous-marin", explanation: "Touret de câble sous-marin de 40 t, reçu avec les arbres de production lors de la même opération (≈ 235 t au total).", color: "#2e7d5b", finish: "paint", explode: [0, 1, -5.6], meshes: [cyl(2, 0.25, [9.5, 3.4, -1.3], [Math.PI / 2, 0, 0]), cyl(2, 0.25, [9.5, 3.4, 1.3], [Math.PI / 2, 0, 0]), cyl(1.4, 2.4, [9.5, 3.4, 0], [Math.PI / 2, 0, 0], "#111")] },
    { name: "Remorque modulaire 10 lignes", explanation: "Remorque hydraulique modulaire Nicolas 10 lignes, d’une capacité de 160 t, du quai 25 du port jusqu’à la base AGL de Vridi.", color: "#4b5566", finish: "metal", explode: [0, -1.2, 0], meshes: [...modular(-4, 10), ...modularWheels(-4, 10)] },
    { name: "Tracteur 6×6 de 500 ch", explanation: "Tracteur 6×6 de 500 chevaux, après une étude de route qui a levé les obstacles sur l’itinéraire.", color: "#f2f2f2", finish: "paint", explode: [3.6, 0.4, 0], meshes: tractor(13.5) },
  ],
  tank_convoy: [
    { name: "Cuve hors gabarit", explanation: "Cuve industrielle hors gabarit pour la brasserie Brakina : deux cuves de 50 t au total, sur plus de 1 300 km d’Abidjan à Ouagadougou.", color: "#d6dde6", finish: "metal", explode: [0, 3.4, 0], meshes: [cyl(2.3, 12, [-1, 3.9, 0], [0, 0, Math.PI / 2]), { shape: "sphere", size: [2.3, 2.3, 2.3], pos: [5, 3.9, 0] }, { shape: "sphere", size: [2.3, 2.3, 2.3], pos: [-7, 3.9, 0] }] },
    { name: "Berceaux de calage", explanation: "Berceaux de calage : ils épousent la forme de la cuve et répartissent la charge sur le plateau sans la déformer.", color: GOLD, finish: "metal", explode: [0, 1.2, 3], meshes: [-5, -1, 3].map(x => box([0.6, 0.9, 3.6], [x, 1.8, 0])) },
    { name: "Remorque surbaissée", explanation: "Remorque surbaissée : elle abaisse la hauteur totale pour passer sous les ponts et les lignes électriques.", color: "#4b5566", finish: "metal", explode: [0, -0.6, 0], meshes: [box([15, 0.4, 3], [-1, 1.15, 0]), ...wheelRow([-6.5, -7.7, -8.9, 4.5], 1.15, 0.5, 0.4)] },
    { name: "Tracteur routier", explanation: "Tracteur routier : 15 jours de convoi, avec un détour de plus de 100 km par Agboville pour éviter les ouvrages incompatibles.", color: "#f2f2f2", finish: "paint", explode: [3.6, 0.4, 0], meshes: tractor(10) },
    { name: "Escorte", explanation: "Véhicules d’escorte : signalisation, régulation de la circulation et guidage aux passages délicats (ponts, péages).", color: "#f2a900", finish: "paint", explode: [4, 0, 3.6], meshes: [box([4.2, 1.6, 2], [21, 1.1, 0]), box([1.4, 0.3, 1.4], [21, 2.05, 0], "#ff7a00", "glass"), ...wheelRow([22.4, 19.6], 0.9, 0.4, 0.3)] },
    { name: "Gabarit et réseau électrique", explanation: "Franchissement du réseau électrique : les lignes basses sont relevées ou mises hors tension en coordination avec les gestionnaires.", color: "#8a96a6", finish: "metal", explode: [0, 2.6, -4], meshes: [box([0.4, 8.5, 0.4], [-11, 4.25, -5]), box([0.4, 8.5, 0.4], [-11, 4.25, 5]), cyl(0.03, 10, [-11, 8.2, 0], [Math.PI / 2, 0, 0], "#111"), cyl(0.03, 10, [-11, 7.6, 0], [Math.PI / 2, 0, 0], "#111")] },
  ],
  terminal: [
    { name: "Quai", explanation: "Quai de 1 100 m avec 16 m de tirant d’eau à Côte d’Ivoire Terminal : il accueille de très grands porte-conteneurs.", color: "#7d8796", finish: "paint", explode: [0, -1.6, 0], meshes: [box([46, 1.2, 14], [0, 0.6, -4])] },
    { name: "Porte-conteneurs", explanation: "Porte-conteneurs à quai : le terminal accueille des navires capables de transporter jusqu’à 24 000 conteneurs.", color: NAVY, finish: "paint", explode: [0, -1, 6], meshes: [box([40, 4, 8], [0, 0.4, 9]), ...range(9, b => b).flatMap(b => [0, 1].flatMap(t => [-2.4, 0, 2.4].map((z, k) => box([3.6, 1.6, 2.2], [-15 + b * 3.8, 3.2 + t * 1.7, 9 + z], STACK[(b + t + k) % STACK.length]))))] },
    { name: "Portiques de quai (STS)", explanation: "Portiques de quai : 8 depuis juillet 2025, les deux derniers entièrement électriques.", color: "#2f6db5", finish: "paint", explode: [0, 4, 0], meshes: [-10, 8].flatMap(x => [box([0.5, 13, 0.5], [x - 3, 7.7, -1]), box([0.5, 13, 0.5], [x + 3, 7.7, -1]), box([0.5, 13, 0.5], [x - 3, 7.7, 5]), box([0.5, 13, 0.5], [x + 3, 7.7, 5]), box([0.9, 0.9, 22], [x, 14.4, 5]), box([2, 0.9, 2], [x, 13.4, 9], GOLD, "metal")]) },
    { name: "Portiques de parc (RTG)", explanation: "Portiques de parc sur pneus : 27 depuis juillet 2025, dont 9 nouveaux entièrement électriques.", color: GOLD, finish: "paint", explode: [0, 3.4, -4], meshes: [-14, 2, 16].flatMap(x => [box([0.4, 7, 0.4], [x - 3, 4.7, -6.5]), box([0.4, 7, 0.4], [x + 3, 4.7, -6.5]), box([0.4, 7, 0.4], [x - 3, 4.7, -0.5]), box([0.4, 7, 0.4], [x + 3, 4.7, -0.5]), box([6.6, 0.6, 0.6], [x, 8.2, -6.5]), box([6.6, 0.6, 0.6], [x, 8.2, -0.5])]) },
    { name: "Parc à conteneurs", explanation: "Parc à conteneurs de 37,5 ha : une capacité de plus de 1,5 million d’EVP par an.", color: "#b23a2a", finish: "paint", explode: [0, 1.6, -5], meshes: range(12, i => i).flatMap(i => range(2, t => t).map(t => box([5.4, 1.4, 2.2], [-18 + (i % 6) * 7, 1.9 + t * 1.45, -6 + Math.floor(i / 6) * 2.8], STACK[(i + t) % STACK.length]))) },
    { name: "Camions de terminal", explanation: "Camions de terminal : ils relient en continu les portiques de quai et les portiques de parc.", color: "#f2f2f2", finish: "paint", explode: [0, 1.2, 3.6], meshes: [-6, 4, 12].flatMap((x, i) => [box([1.6, 1.6, 1.6], [x + 2.2, 2, 2.4]), box([4.4, 0.4, 1.8], [x, 1.4, 2.4], "#4a5260", "metal"), box([4, 1.3, 2], [x - 0.4, 2.25, 2.4], STACK[i % STACK.length])]) },
  ],
  mri: [
    { name: "Capots", explanation: "Capots extérieurs : ils protègent les équipements et facilitent le nettoyage en milieu hospitalier.", color: "#f4f6f9", finish: "paint", explode: [0, 0, -3.4], meshes: [box([1.6, 2.6, 2.7], [0, 1.5, 0])] },
    { name: "Aimant supraconducteur", explanation: "Aimant supraconducteur dans son cryostat refroidi à l’hélium liquide : la pièce la plus lourde et la plus sensible, à manipuler sans choc.", color: "#9aa6b8", finish: "metal", explode: [-3, 0, 0], meshes: [cyl(1.1, 1.5, [0, 1.5, 0], [0, 0, Math.PI / 2])] },
    { name: "Bobines de gradient", explanation: "Bobines de gradient : elles font varier le champ magnétique pour localiser le signal et construire l’image en coupes.", color: GOLD, finish: "metal", explode: [3, 0, 0], meshes: [cyl(0.82, 1.4, [0, 1.5, 0], [0, 0, Math.PI / 2])] },
    { name: "Antenne radiofréquence", explanation: "Antenne radiofréquence : elle émet les impulsions et capte le signal renvoyé par les tissus.", color: "#5b8fd0", finish: "metal", explode: [5.2, 0.6, 0], meshes: [cyl(0.6, 1.2, [0, 1.5, 0], [0, 0, Math.PI / 2])] },
    { name: "Tête froide", explanation: "Tête froide du cryocompresseur : elle maintient l’hélium à très basse température.", color: "#3b4250", finish: "metal", explode: [0, 2.2, 0], meshes: [cyl(0.2, 0.8, [0, 3, 0])] },
    { name: "Table patient", explanation: "Table patient motorisée : elle positionne la zone à examiner au centre de l’aimant.", color: "#e8edf3", finish: "paint", explode: [0, 0, 3.4], meshes: [box([3.6, 0.15, 0.7], [2.6, 1.05, 0]), box([0.8, 0.9, 0.6], [3.6, 0.45, 0], "#cfd6e0")] },
    { name: "Socle de transport", explanation: "Socle et calage de transport : trois IRM, plus de 32 t d’équipements, levées et positionnées dans les CHU de Cocody, Treichville et Angré.", color: "#6b4f2a", explode: [0, -1.2, 0], meshes: [box([2.8, 0.25, 2.8], [0, 0.12, 0])] },
  ],
  haul_truck: [
    { name: "Benne", explanation: "Benne basculante : elle transporte le minerai ou les stériles depuis le front de taille.", color: "#e3b500", finish: "paint", explode: [0, 4.6, 0], meshes: [box([8, 2.6, 5.6], [-1.6, 5.2, 0]), box([2.6, 0.3, 5.6], [3.6, 6.4, 0])] },
    { name: "Vérins de levage", explanation: "Vérins hydrauliques : ils basculent la benne pour vider la charge au concasseur ou à la verse.", color: "#cfd6e0", finish: "metal", explode: [0, 2.2, 3.6], meshes: [cyl(0.25, 2.6, [0.6, 3.4, -1.6], [0, 0, 0.5]), cyl(0.25, 2.6, [0.6, 3.4, 1.6], [0, 0, 0.5])] },
    { name: "Cabine", explanation: "Cabine surélevée : visibilité dégagée sur un engin de plusieurs mètres de haut.", color: "#f2f2f2", finish: "paint", explode: [2.6, 2.6, -2.4], meshes: [box([1.8, 1.8, 1.8], [4.4, 5.4, -1.6]), box([0.06, 0.9, 1.4], [5.32, 5.6, -1.6], "#9fc3ea", "glass")] },
    { name: "Moteur et radiateur", explanation: "Moteur et radiateur à l’avant : la puissance nécessaire pour gravir les rampes de la mine en charge.", color: "#4a5260", finish: "metal", explode: [4, 0.6, 0], meshes: [box([2.4, 2.4, 3.4], [4.6, 2.9, 0]), box([0.2, 2, 3], [5.9, 2.9, 0], "#5b6470")] },
    { name: "Châssis", explanation: "Châssis renforcé : il encaisse les chocs du chargement par pelle ou chargeuse.", color: "#3b4250", finish: "metal", explode: [0, 0.4, 0], meshes: [box([10, 0.8, 2.4], [0, 2.4, 0])] },
    { name: "Roues géantes", explanation: "Pneus géants : leur taille dépasse souvent celle d’un adulte, d’où des convois exceptionnels pour livrer ces engins sur site.", color: "#22272f", finish: "rubber", explode: [0, -1.8, 0], meshes: [...wheelRow([4.2], 2.1, 1.6, 1.2, 1.6), ...wheelRow([-3.8], 1.6, 1.6, 1, 1.6), ...wheelRow([-3.8], 2.7, 1.6, 1, 1.6)] },
  ],
};
