"use client";
import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Mic, MicOff, X, Send, Eye, Camera, VolumeX } from "lucide-react";
import { useKiosk, logEvent } from "@/lib/store";
import { useGeminiLive } from "@/lib/use-gemini-live";
import { askStream, playServerVoice, stopServerVoice, preferredModel } from "@/lib/live";
import { Orb } from "./Orb";

interface Msg { role:"user"|"ai"; text:string }
export function AIAssistant(){
  const k=useKiosk();const en=k.lang==="en";const [messages,setMessages]=useState<Msg[]>([]);const [input,setInput]=useState("");const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");const bottom=useRef<HTMLDivElement>(null);const controller=useRef<AbortController|null>(null);const busyRef=useRef(false);const msgs=useRef(messages);msgs.current=messages;const current=useRef(k);current.current=k;const pending=useRef("");const liveUser=useRef(-1);const liveReply=useRef(-1);
  const live=useGeminiLive({lang:k.lang,getContext:()=>current.current.getExperienceContext(),onActivity:()=>current.current.touch(),onUser:(text)=>{if(liveUser.current<0){liveUser.current=msgs.current.length;setMessages(m=>[...m,{role:"user",text}]);}else setMessages(m=>m.map((v,i)=>i===liveUser.current?{role:"user",text}:v));},onReply:(text,done)=>{if(text){if(liveReply.current<0){liveReply.current=msgs.current.length;setMessages(m=>[...m,{role:"ai",text}]);}else setMessages(m=>m.map((v,i)=>i===liveReply.current?{role:"ai",text}:v));}if(done){liveReply.current=-1;liveUser.current=-1;}}});
  useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"});},[messages]);
  useEffect(()=>{const state=live.phase==="connecting"?"thinking":live.phase;k.setAiState(state);},[live.phase,k.setAiState]);
  useEffect(()=>{if(k.pendingQuestion&&pending.current!==k.pendingQuestion){pending.current=k.pendingQuestion;void ask(k.pendingQuestion.replace(/^\d+::/,""));}},[k.pendingQuestion]);
  useEffect(()=>()=>{controller.current?.abort();stopServerVoice();},[]);
  useEffect(()=>{if(!k.aiOpen){live.stop();controller.current?.abort();stopServerVoice();}},[k.aiOpen]);
  const greetings=en?"Hi, I’m AGL AI. Ask me about Mining, show a corridor or prepare your next step with AGL.":"Bonjour, je suis AGL AI. Parlons Mining, affichons un corridor ou préparons votre prochaine étape avec AGL.";
  async function ask(text:string){
    if(!text.trim()||busyRef.current)return;live.stop();stopServerVoice();k.touch();busyRef.current=true;setBusy(true);setInput("");setStatus(en?"Connecting to Gemini…":"Connexion à Gemini…");k.setAiState("thinking");logEvent("ai_question",{screen:k.screen});
    const history=msgs.current.slice(-12);const index=history.length;setMessages([...history,{role:"user",text},{role:"ai",text:""}]);const abort=new AbortController();controller.current=abort;
    try{const meta=await askStream({message:text,context:k.getExperienceContext(),history,lang:k.lang,model:preferredModel()},full=>{setStatus(en?"Gemini is answering":"Gemini répond");setMessages(m=>m.map((v,i)=>i===index+1?{role:"ai",text:full}:v));},abort.signal);if(abort.signal.aborted)return;setMessages(m=>m.map((v,i)=>i===index+1?{role:"ai",text:meta.reply}:v));k.setLastAiReply(meta.reply);setStatus(meta.degraded?(en?"AI unavailable — experiences remain accessible":"IA indisponible — les expériences restent accessibles"):`${meta.model}`);if(k.soundOn&&!meta.degraded){k.setAiState("speaking");const ok=await playServerVoice(meta.reply,k.lang);if(!ok&&!abort.signal.aborted&&typeof speechSynthesis!=="undefined"){const u=new SpeechSynthesisUtterance(meta.reply);u.lang=en?"en-US":"fr-FR";speechSynthesis.speak(u);}}}
    catch{if(!abort.signal.aborted){setStatus(en?"Connection unavailable. Please try again.":"Connexion indisponible. Réessayez dans un instant.");setMessages(m=>m.filter((v,i)=>i!==index+1||v.text));}}
    finally{busyRef.current=false;setBusy(false);k.setAiState("idle");}
  }
  const suggestions=k.screen==="mining"?(en?["Explain this mining stage","Show the construction stage","Open the Tokadeh case"]:["Explique cette étape minière","Affiche l’étape construction","Explique le cas Tokadeh"]):(en?["Show the multimodal corridor","What can AGL do for my mine?","Open an appointment"]:["Affiche le corridor multimodal","Que peut faire AGL pour ma mine ?","Ouvre un rendez-vous"]);
  const orbState=live.active?(live.phase==="connecting"?"thinking":live.phase):k.aiState;
  return <><button className="ai-launcher" onClick={()=>{k.setAiOpen(true);k.touch();}} aria-label="Ouvrir AGL AI"><Orb size={36} state={orbState}/><span>AGL AI · {en?"Let’s talk":"Parlons ensemble"}</span></button><AnimatePresence>{k.aiOpen&&<motion.aside className="ai-panel" initial={{x:520,opacity:0}} animate={{x:0,opacity:1}} exit={{x:520,opacity:0}} transition={{duration:.35}} aria-label="Assistant AGL AI"><header><div><h2>AGL AI</h2><p className="ai-status">{live.active?`${live.model||"Gemini Live"} · ${live.phase}`:(status|| (en?"Your logistics guide":"Votre guide logistique"))}</p></div><button className="ai-icon-btn" aria-label="Fermer AGL AI" onClick={()=>{live.stop();k.setAiOpen(false);}}><X size={22}/></button></header><div className="ai-messages"><div className="ai-message">{greetings}</div>{messages.map((m,i)=><div key={i} className={`ai-message ${m.role==="user"?"user":""}`}>{m.text||<span style={{color:"#aabbd2"}}>{en?"Thinking…":"Je réfléchis…"}</span>}</div>)}{live.error&&<p className="ai-status" role="status">{live.error}</p>}<div ref={bottom}/></div><footer><div className="ai-suggestions">{suggestions.map(s=><button disabled={busy} key={s} onClick={()=>ask(s)}>{s}</button>)}</div><div className="ai-input-row"><button className={`ai-icon-btn ${live.active?"gold":""}`} disabled={busy} title={en?"Live voice conversation":"Conversation vocale Live"} onClick={()=>{k.touch();live.active?live.stop():live.start();logEvent("voice_used",{mode:"native-live"});}}>{live.active?<MicOff size={23}/>:<Mic size={23}/>}</button><input aria-label="Question à AGL AI" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")ask(input);}} placeholder={en?"Ask your question…":"Votre question…"}/><button className="ai-icon-btn gold" disabled={busy||!input.trim()} aria-label="Envoyer la question" onClick={()=>ask(input)}><Send size={21}/></button></div><div className="button-row" style={{marginTop:10,gap:8}}><button className="text-action" disabled={busy} onClick={()=>ask(en?"Explain what is on my screen.":"Explique ce que je vois à l’écran.")}><Eye size={18}/>{en?"This screen":"Cet écran"}</button><button className="text-action" onClick={()=>{live.stop();k.setAiOpen(false);k.go("vision");}}><Camera size={18}/>{en?"Camera & voice":"Caméra & voix"}</button><button className="ai-icon-btn" style={{minWidth:44,minHeight:44,marginLeft:"auto"}} aria-label="Interrompre la réponse" onClick={()=>{live.interrupt();stopServerVoice();controller.current?.abort();}}><VolumeX size={18}/></button></div><p className="ai-status">{en?"Live audio needs microphone permission. No conversations are saved.":"Le mode Live demande l’accès au micro. Les conversations ne sont pas enregistrées."}</p></footer></motion.aside>}</AnimatePresence></>;
}
