"use client";
import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Mic, MicOff, X, Send, Eye, Camera, VolumeX, Brain } from "lucide-react";
import { useKiosk, logEvent } from "@/lib/store";
import { useLiveVoice, LIVE_PHASE_LABEL } from "@/lib/use-gemini-live";
import { askStream, playServerVoice, stopServerVoice, preferredModel, speakLocal } from "@/lib/live";
import { Orb } from "./Orb";
import { sfx } from "@/lib/sound";

interface Msg { role:"user"|"ai"; text:string }
export function AIAssistant(){
  const k=useKiosk();const en=k.lang==="en";const [messages,setMessages]=useState<Msg[]>([]);const [input,setInput]=useState("");const [busy,setBusy]=useState(false);const [deep,setDeep]=useState(false);const [status,setStatus]=useState("");const bottom=useRef<HTMLDivElement>(null);const controller=useRef<AbortController|null>(null);const busyRef=useRef(false);const msgs=useRef(messages);msgs.current=messages;const current=useRef(k);current.current=k;const pending=useRef("");const liveUser=useRef(-1);const liveReply=useRef(-1);const [writing,setWriting]=useState(-1);
  const live=useLiveVoice({lang:k.lang,getContext:()=>current.current.getExperienceContext(),onActivity:()=>current.current.touch(),onUser:(text)=>{if(liveUser.current<0){liveUser.current=msgs.current.length;setMessages(m=>[...m,{role:"user",text}]);}else setMessages(m=>m.map((v,i)=>i===liveUser.current?{role:"user",text}:v));},onReply:(text,done)=>{setWriting(done||!text?-1:liveReply.current<0?msgs.current.length:liveReply.current);if(text){if(liveReply.current<0){liveReply.current=msgs.current.length;setMessages(m=>[...m,{role:"ai",text}]);}else setMessages(m=>m.map((v,i)=>i===liveReply.current?{role:"ai",text}:v));}if(done){liveReply.current=-1;liveUser.current=-1;}}});
  useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"});},[messages]);
  useEffect(()=>{const state=live.phase==="connecting"?"thinking":live.phase;k.setAiState(state);},[live.phase,k.setAiState]);
  const prevPhase=useRef(live.phase);useEffect(()=>{if(prevPhase.current==="connecting"&&live.phase==="listening")sfx("live");prevPhase.current=live.phase;},[live.phase]);
  useEffect(()=>{if(k.aiOpen)sfx("open");},[k.aiOpen]);
  useEffect(()=>{if(k.pendingQuestion&&pending.current!==k.pendingQuestion){pending.current=k.pendingQuestion;void ask(k.pendingQuestion.replace(/^\d+::/,""));}},[k.pendingQuestion]);
  useEffect(()=>()=>{controller.current?.abort();stopServerVoice();},[]);
  useEffect(()=>{if(!k.aiOpen){live.stop();controller.current?.abort();stopServerVoice();}},[k.aiOpen]);
  const greetings=en?"Hi, I’m Lara. Ask me about Mining, see a corridor come alive or prepare your next step with Africa Global Logistics.":"Bonjour, je suis Lara. Parlons Mining, donnons vie à un corridor ou préparons votre prochaine étape avec Africa Global Logistics.";
  async function ask(text:string){
    if(!text.trim()||busyRef.current)return;live.stop();stopServerVoice();k.touch();busyRef.current=true;setBusy(true);setInput("");setStatus(en?"Connecting to Lara…":"Connexion à Lara…");k.setAiState("thinking");logEvent("ai_question",{screen:k.screen,deep});
    const history=msgs.current.slice(-12);const index=history.length;setMessages([...history,{role:"user",text},{role:"ai",text:""}]);const abort=new AbortController();controller.current=abort;setWriting(index+1);
    try{const meta=await askStream({message:text,context:k.getExperienceContext(),history,lang:k.lang,model:preferredModel(),deepThink:deep},full=>{setStatus(en?"Lara is answering":"Lara répond");setMessages(m=>m.map((v,i)=>i===index+1?{role:"ai",text:full}:v));},abort.signal);if(abort.signal.aborted)return;setMessages(m=>m.map((v,i)=>i===index+1?{role:"ai",text:meta.reply}:v));k.setLastAiReply(meta.reply);setStatus(meta.degraded?(en?"AI unavailable — experiences remain accessible":"IA indisponible — les expériences restent accessibles"):(en?"Ready":"Prêt"));if(k.soundOn&&!meta.degraded){k.setAiState("speaking");const ok=await playServerVoice(meta.reply,k.lang);if(!ok&&!abort.signal.aborted)speakLocal(meta.reply,k.lang);}}
    catch{if(!abort.signal.aborted){setStatus(en?"Connection unavailable. Please try again.":"Connexion indisponible. Réessayez dans un instant.");setMessages(m=>m.filter((v,i)=>i!==index+1||v.text));}}
    finally{busyRef.current=false;setBusy(false);setWriting(-1);k.setAiState("idle");}
  }
  const suggestions=k.screen==="mining"?(en?["Explain this mining stage","Show the construction stage","Open the Tokadeh case"]:["Explique cette étape minière","Affiche l’étape construction","Explique le cas Tokadeh"]):(en?["Plan 80 t of mining equipment to Korhogo","Show the multimodal corridor","What can Africa Global Logistics do for my mine?"]:["Organise 80 t d’équipement minier vers Korhogo","Affiche le corridor multimodal","Que peut faire Africa Global Logistics pour ma mine ?"]);
  const orbState=live.active?(live.phase==="connecting"?"thinking":live.phase):k.aiState;
  const statusLine=live.active?`${en?"Voice":"Voix"} · ${LIVE_PHASE_LABEL[live.phase][en?"en":"fr"]}`:(status||(en?"Your logistics guide":"Votre guide logistique"));
  const glowing=writing>=0||orbState==="speaking";
  return <><button className="ai-launcher" onClick={()=>{k.setAiOpen(true);k.touch();logEvent("voice_used",{mode:"launcher"});void live.start();}} aria-label="Ouvrir Lara"><Orb size={36} state={orbState}/><span>Lara · {en?"Let’s talk":"Parlons ensemble"}</span></button>
  <AnimatePresence>{k.aiOpen&&<motion.aside className={`ai-panel glass ${glowing?"is-writing":""}`} initial={{x:40,opacity:0,scale:.98}} animate={{x:0,opacity:1,scale:1}} exit={{x:40,opacity:0,scale:.98}} transition={{duration:.32,ease:[0.22,1,0.36,1]}} aria-label="Assistante Lara">
    <header><div className="ai-head"><Orb size={18} state={orbState}/><div><h2>Lara</h2><p className="ai-status ai-live-status" aria-live="polite"><i className={`ai-pulse ${orbState}`}/>{statusLine}</p></div></div><button className="ai-ghost" aria-label="Fermer Lara" onClick={()=>{live.stop();k.setAiOpen(false);}}><X size={20}/></button></header>
    <div className="ai-messages"><div className="ai-message lead"><span className="ai-sign">Lara</span>{greetings}</div>{messages.map((m,i)=>{const prev=i===0?"ai":messages[i-1].role;const lead=prev!==m.role;return <motion.div key={i} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.3,ease:[0.22,1,0.36,1]}} className={`ai-message ${m.role==="user"?"user":""} ${lead?"lead":"follow"} ${i===writing?"writing":""}`}>{lead&&m.role==="ai"&&<span className="ai-sign">Lara</span>}{m.text||<span className="ai-dots" aria-label={en?"Thinking":"Je réfléchis"}><i/><i/><i/></span>}</motion.div>;})}{live.error&&<p className="ai-status" role="status">{live.error}</p>}<div ref={bottom}/></div>
    <footer><div className="ai-suggestions">{suggestions.map(s=><button disabled={busy} key={s} onClick={()=>ask(s)}>{s}</button>)}</div>
      <div className="ai-input-row"><button className={`ai-round ${live.active?"on":""}`} disabled={busy} aria-label={en?"Voice conversation":"Conversation vocale"} title={en?"Voice conversation":"Conversation vocale"} onClick={()=>{k.touch();live.active?live.stop():live.start();logEvent("voice_used",{mode:"native-live"});}}>{live.active?<MicOff size={20}/>:<Mic size={20}/>}</button><input aria-label="Question à Lara" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")ask(input);}} placeholder={en?"Ask Lara…":"Demandez à Lara…"}/><button className="ai-round send" disabled={busy||!input.trim()} aria-label="Envoyer la question" onClick={()=>ask(input)}><Send size={18}/></button></div>
      <div className="ai-tools"><button className="ai-ghost" aria-pressed={deep} disabled={busy} aria-label={en?"Deep thinking":"Réflexion approfondie"} title={en?"Deep thinking":"Réflexion approfondie"} onClick={()=>setDeep(!deep)}><Brain size={18}/></button><button className="ai-ghost" disabled={busy} aria-label={en?"This screen":"Cet écran"} title={en?"This screen":"Cet écran"} onClick={()=>ask(en?"Explain what is on my screen.":"Explique ce que je vois à l’écran.")}><Eye size={18}/></button><button className="ai-ghost" aria-label={en?"Camera & voice":"Caméra & voix"} title={en?"Camera & voice":"Caméra & voix"} onClick={()=>{live.stop();k.setAiOpen(false);k.go("vision");}}><Camera size={18}/></button><button className="ai-ghost" aria-label="Interrompre la réponse" title={en?"Stop":"Interrompre"} onClick={()=>{live.interrupt();stopServerVoice();controller.current?.abort();}}><VolumeX size={18}/></button><span className="ai-note">{en?"No conversation is saved":"Aucune conversation enregistrée"}</span></div>
    </footer></motion.aside>}</AnimatePresence></>;
}
