"use client";
import { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import { Pickaxe, Truck, Warehouse, TrainFront, Anchor, Ship, Bot, ArrowRight } from "lucide-react";
import { useKiosk } from "@/lib/store";
import { TopBar } from "./Chrome";
const RealCivMap=dynamic(()=>import("./RealMaps").then(m=>m.RealCivMap),{ssr:false});
const nodes=[{id:"mine",icon:Pickaxe,title:"SITE MINIER",image:"image19",text:"Équipements, production et approvisionnements à coordonner sur un site parfois isolé.",en:"Equipment, production and supply must be coordinated, often at a remote site.",exp:["Project logistics","Route surveys","QHSE"]},{id:"truck",icon:Truck,title:"TRANSPORT ROUTIER",image:"image19",text:"Organiser le passage entre les points de collecte, les hubs et les infrastructures de sortie.",en:"Coordinate movements between collection points, hubs and outbound infrastructure.",exp:["Road transport","Heavy haulage","Tracking"]},{id:"hub",icon:Warehouse,title:"HUB LOGISTIQUE",image:"image15",text:"Consolider, stocker, contrôler et préparer les marchandises et leurs documents.",en:"Consolidate, store, check and prepare goods and their documents.",exp:["Warehousing","Inventory management","Consolidation"]},{id:"rail",icon:TrainFront,title:"RAIL",image:"image24",text:"Massifier les flux compatibles avec l’infrastructure et coordonner les ruptures de charge.",en:"Consolidate flows compatible with infrastructure and coordinate transfer points.",exp:["Rail logistics","Multimodal coordination","Corridor management"]},{id:"port",icon:Anchor,title:"PORT & TERMINAL",image:"image26",text:"Coordonner réception, manutention, formalités et connexion au transport maritime.",en:"Coordinate reception, handling, formalities and the maritime connection.",exp:["Terminal operations","Cargo handling","Customs coordination"]},{id:"ship",icon:Ship,title:"NAVIRE",image:"image18",text:"Relier les flux africains aux marchés internationaux dans une chaîne suivie et coordonnée.",en:"Connect African flows with international markets through a tracked, coordinated chain.",exp:["Freight forwarding","Maritime connectivity","Supply-chain visibility"]}];
export function ExploreScreen(){const k=useKiosk();const en=k.lang==="en";const [i,setI]=useState(0);const n=nodes[i];useEffect(()=>{k.setSelectedNode(n.id);k.setContextDetails({node:n.title,capabilities:n.exp,simulation:true,xray:k.xray,dataView:k.dataView});},[i,k.xray,k.dataView,k.setContextDetails,k.setSelectedNode]);return <div className="experience-page"><TopBar title="EXPLORE AGL" subtitle={en?"Follow the physical flow. Reveal the information flow.":"Suivez le flux physique. Révélez le flux d’information."}/><main className="experience-content"><div className="stage-tabs">{nodes.map((p,index)=><button key={p.id} className={i===index?"active":""} onClick={()=>setI(index)}><p.icon size={20}/>{p.title}</button>)}</div><div className="mining-layout"><div className="panel" style={{padding:16}}><RealCivMap selectedRoute="route-B"/><div className="button-row"><button className="outline-btn" onClick={()=>k.setXray(!k.xray)}>X-RAY · {k.xray?"ON":"OFF"}</button><button className="outline-btn" onClick={()=>k.setDataView(!k.dataView)}>DATA VIEW · {k.dataView?"ON":"OFF"}</button></div>{k.xray&&<div className="pill-row" style={{marginTop:16}}>{["Marchandise","Documents","Données","Douane","Équipes"].map((p,j)=><span className="pill" style={{borderColor:["#EED58E","#7fb3e8","#7be2ac","#c99cff","#ffa7a7"][j]}} key={p}>{p} →</span>)}</div>}{k.dataView&&<div className="panel" style={{marginTop:16,fontSize:13}}><span className="eyebrow">DONNÉES DE DÉMONSTRATION</span><p>Shipment AGL-DEMO · IN TRANSIT</p><p>Documents · contrôle avant livraison</p><p>Alerte · coordination du prochain transfert</p><p className="ai-status">Aucun suivi opérationnel réel sur cette borne.</p></div>}</div><div><img src={`/assets/template/${n.image}.webp`} alt="" style={{width:"100%",height:230,objectFit:"cover",borderRadius:20,marginBottom:18}}/><div className="panel"><span className="eyebrow">AGL EXPERTISE · {i+1}/6</span><h3 style={{fontSize:28,marginTop:12}}>{n.title}</h3><p style={{lineHeight:1.7,color:"#d3dfef"}}>{en?n.en:n.text}</p><div className="pill-row" style={{marginTop:18}}>{n.exp.map(p=><span className="pill" key={p}>{p}</span>)}</div><div className="button-row"><button className="brand-btn" onClick={()=>i<5?setI(i+1):(k.setFinaleStats({Expérience:"Explore AGL",Maillons:6}),k.go("satisfaction"))}>{i<5?(en?"Next link":"Maillon suivant"):(en?"Finish & give feedback":"Terminer & donner mon avis")}<ArrowRight size={18}/></button><button className="outline-btn" onClick={()=>k.requestAI(en?`Explain the role of ${n.title} at this stage.`:`Explique le rôle de ${n.title} à cette étape.`)}><Bot size={20}/>AGL AI</button></div></div></div></div><p className="ai-status" style={{marginTop:18}}>Carte géographique réelle, corridor et flux illustratifs. Faisabilité de chaque solution à étudier.</p></main></div>;}
