"use client";
import { useEffect, useState } from "react";
import QRCode from "qrcode";
import { ExternalLink, Home, RotateCw, CheckCircle2 } from "lucide-react";
import { SATISFACTION_URL, QUOTATION_URL } from "@/lib/content";
import { useKiosk, logEvent } from "@/lib/store";
import { TopBar } from "./Chrome";

export function ExternalExperience({ kind }: {kind:"satisfaction"|"quotation"}) {
  const k=useKiosk();const en=k.lang==="en";const survey=kind==="satisfaction";const url=survey?SATISFACTION_URL:QUOTATION_URL;const [qr,setQr]=useState("");const [reload,setReload]=useState(0);
  useEffect(()=>{QRCode.toDataURL(url,{width:180,margin:1,color:{dark:"#1B365F",light:"#FFFFFF"}}).then(setQr);logEvent(survey?"satisfaction_opened":"quotation_opened",{});},[url,survey]);
  // Parent cannot inspect cross-origin forms. Keep a visible direct-link/QR fallback at all times.
  return <div className="embedded-page"><TopBar title={survey?(en?"YOUR FEEDBACK MATTERS":"VOTRE AVIS COMPTE"):(en?"REQUEST A QUOTATION":"DEMANDER UNE COTATION")} subtitle={survey?"AGL · Microsoft Forms":"Africa Global Logistics · Formulaire officiel"}/><div className="embedded-toolbar"><div><h2>{survey?(en?"Thank you for exploring with AGL.":"Merci d’avoir exploré avec AGL."):(en?"Tell AGL about your shipment.":"Décrivez votre besoin de transport à AGL.")}</h2><p>{survey?(en?"The satisfaction survey opens below. You can also scan the QR code.":"L’enquête de satisfaction s’ouvre ci-dessous. Vous pouvez aussi scanner le QR code."):(en?"The official quotation page opens below.":"La page de cotation officielle s’ouvre ci-dessous.")}</p>{survey&&k.finaleStats&&<div className="pill-row" style={{marginTop:10}}>{Object.entries(k.finaleStats).map(([key,v])=><span className="pill" key={key}>{key} · {v}</span>)}</div>}</div><div className="embed-actions">{qr&&<img className="qr-image" src={qr} alt="QR code du formulaire"/>}<a href={url} target="_blank" rel="noopener noreferrer"><ExternalLink size={18}/>{en?"Open full page":"Ouvrir en pleine page"}</a><button onClick={()=>setReload(reload+1)} aria-label="Recharger le formulaire"><RotateCw size={18}/></button><button onClick={()=>k.go("home")}><Home size={18}/>{en?"Home":"Accueil"}</button></div></div><div className="embed-hint">{en?"If the form is not displayed, use “Open full page” or the QR code. Submission is managed by the official external service.":"Si le formulaire ne s’affiche pas, utilisez « Ouvrir en pleine page » ou le QR code. La validation est gérée par le service externe officiel."}</div><iframe key={reload} className="embedded-iframe" src={url+(survey?"&embed=true":"")} title={survey?"Enquête de satisfaction AGL":"Demande de cotation AGL"} allow="clipboard-write" referrerPolicy="strict-origin-when-cross-origin" onLoad={()=>k.touch()}/>{!survey&&<div className="embedded-toolbar" style={{justifyContent:"flex-end"}}><button className="brand-btn" onClick={()=>k.go("satisfaction")}><CheckCircle2 size={18}/>{en?"Continue to the survey":"Continuer vers l’enquête"}</button></div>}</div>;
}
