"use client";
import { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import { X, Download, ArrowRight } from "lucide-react";
import { useKiosk } from "@/lib/store";
import { type MaterialAction } from "@/lib/actions";
import { downloadFile } from "@/lib/requests";
const RealCivMap=dynamic(()=>import("./RealMaps").then(m=>m.RealCivMap),{ssr:false,loading:()=> <div className="h-[420px] md:h-[480px] grid place-items-center">Chargement de la carte…</div>});
export function MaterialHost(){const k=useKiosk();const [sheet,setSheet]=useState<MaterialAction|null>(null);
  useEffect(()=>{const handle=(e:Event)=>{const a=(e as CustomEvent<MaterialAction>).detail;if(a.type==="go")k.go(a.screen);if(a.type==="show_mining"){sessionStorage.setItem("agl-mining-stage",a.stage);k.go("mining");window.dispatchEvent(new CustomEvent("agl-mining-stage",{detail:a.stage}));}if(a.type==="show_route"){k.setRoute(a.route);setSheet(a);}if(a.type==="sheet"||a.type==="show_image")setSheet(a);};window.addEventListener("agl-action",handle);return()=>window.removeEventListener("agl-action",handle);},[k.go,k.setRoute]);
  if(!sheet)return null;const route=sheet.type==="show_route";const title=route?`Corridor ${sheet.route.replace("route-","")} · Côte d’Ivoire`:sheet.type==="sheet"?sheet.title:sheet.type==="show_image"?sheet.title:"Africa Global Logistics";
  return <div style={{position:"fixed",inset:0,background:"#0008",zIndex:80,display:"grid",placeItems:"center",padding:24}}><div className="panel" style={{width:"min(950px,100%)",maxHeight:"90dvh",overflow:"auto",background:"#1b365f"}} role="dialog" aria-modal="true" aria-label={title}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:16}}><div><span className="eyebrow">Lara · VUE MATÉRIALISÉE</span><h3 style={{margin:0}}>{title}</h3></div><button className="ai-icon-btn" aria-label="Fermer la fiche" onClick={()=>setSheet(null)}><X/></button></div>{route?<><RealCivMap selectedRoute={sheet.route} onSelectRoute={r=>{k.setRoute(r);setSheet({type:"show_route",route:r as "route-A"});}}/><p className="ai-status">Liaison de principe entre des villes réelles. Itinéraire et faisabilité à valider par une étude de route.</p></>:sheet.type==="sheet"?<p style={{fontSize:18,lineHeight:1.8,whiteSpace:"pre-wrap"}}>{sheet.body}</p>:sheet.type==="show_image"?<><img src={sheet.image} alt="Visuel généré" style={{width:"100%",borderRadius:16}}/><p className="ai-status">Illustration générée à la demande par Lara — visuel indicatif, pas une photo contractuelle.</p></>:null}<div className="button-row"><button className="outline-btn" onClick={()=>{if(sheet.type==="show_image"){const a=document.createElement("a");a.href=sheet.image;a.download="Lara-image.png";a.click();}else downloadFile("Africa Global Logistics-fiche.txt",title+"\n\n"+(sheet.type==="sheet"?sheet.body:"Corridor illustratif — étude de route nécessaire."));}}><Download size={18}/>{sheet.type==="show_image"?"Télécharger l’image":"Télécharger la fiche"}</button><button className="brand-btn" onClick={()=>{setSheet(null);k.go(route?"mission":"appointment");}}>Continuer<ArrowRight size={18}/></button></div></div></div>;
}
