"use client";
import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, Compass, Construction, Factory, Leaf, Ship, Pickaxe, Bot, Download } from "lucide-react";
import { motion } from "framer-motion";
import { useKiosk, logEvent } from "@/lib/store";
import { MINING_STAGES, TOKADEH } from "@/lib/content";
import { downloadFile } from "@/lib/requests";
import { TopBar } from "./Chrome";

const ICONS=[Compass,Construction,Factory,Ship,Leaf];
const questions=[
  {q:"Un équipement hors gabarit doit rejoindre un site isolé. Quelle est la première décision ?",qEn:"Oversized equipment must reach a remote site. What comes first?",choices:["Étudier la route, les ouvrages et les risques","Choisir uniquement le camion le plus grand","Partir immédiatement pour gagner du temps"],choicesEn:["Study access, structures and risks","Only choose the largest truck","Depart immediately to save time"],correct:0,why:"Une étude de route et une analyse des risques permettent de vérifier l’accès, les capacités des ouvrages et les moyens spécialisés nécessaires.",whyEn:"A route survey and risk assessment check access, structure capacity and the specialised equipment required."},
  {q:"Des équipements arrivent de plusieurs origines. Que doit-on synchroniser ?",qEn:"Equipment arrives from multiple origins. What should be synchronised?",choices:["Seulement le dernier kilomètre","Fret, douane, stockage et livraison sur site","Uniquement l’heure d’arrivée du navire"],choicesEn:["Only the last mile","Freight, customs, storage and onsite delivery","Only the vessel arrival time"],correct:1,why:"La coordination des flux limite les ruptures : fret, formalités, yards, opérations de levage et disponibilité des équipes sur site.",whyEn:"Coordinated flows reduce disruption across freight, clearance, yards, lifting operations and onsite team readiness."},
  {q:"Qu’est-ce qui sécurise une chaîne logistique minière ?",qEn:"What secures a mining supply chain?",choices:["Le prix seul","Un seul mode pour toutes les cargaisons","QHSE, conformité, visibilité et coordination locale"],choicesEn:["Price alone","One transport mode for all cargo","QHSE, compliance, visibility and local coordination"],correct:2,why:"La performance repose sur l’orchestration : exigences QHSE, conformité réglementaire, suivi des flux et mobilisation des partenaires locaux.",whyEn:"Performance comes from orchestration: QHSE, regulatory compliance, flow visibility and local partner coordination."},
];
export function MiningScreen() {
  const k=useKiosk(); const en=k.lang==="en"; const [stage,setStage]=useState(0); const [mode,setMode]=useState<"lifecycle"|"case"|"quiz">("lifecycle"); const [q,setQ]=useState(0); const [answer,setAnswer]=useState<number|null>(null); const [score,setScore]=useState(0);
  const s=MINING_STAGES[stage]; const Q=questions[q];
  useEffect(()=>{const activate=(id:string)=>{const n=MINING_STAGES.findIndex(s=>s.id===id);if(n>=0){setMode("lifecycle");setStage(n);}};const id=sessionStorage.getItem("agl-mining-stage");if(id){activate(id);sessionStorage.removeItem("agl-mining-stage");}const handler=(e:Event)=>activate((e as CustomEvent<string>).detail);window.addEventListener("agl-mining-stage",handler);return()=>window.removeEventListener("agl-mining-stage",handler);},[]);
  useEffect(()=>{k.setContextDetails({sector:"mining",mode,lifecycleStage:s.id,capabilities:s.capabilities,case:mode==="case"?TOKADEH:undefined,question:mode==="quiz"?Q.q:undefined});},[mode,stage,q,k.setContextDetails]);
  const finish=()=>{logEvent("mining_completed",{score});k.setFinaleStats({Expérience:"Mining",Score:`${score} / 3`});k.go("satisfaction");};
  return <div className="experience-page"><TopBar title="MINING JOURNEY" subtitle={en?"Integrated logistics throughout the mining lifecycle":"La logistique intégrée, à chaque étape du cycle minier"}/><main className="experience-content">
    <div className="section-heading"><div><span className="eyebrow">MINING · AFRICA GLOBAL LOGISTICS EXPERTISE</span><h2>{en?"From exploration to opportunity.":"De l’exploration à l’opportunité."}</h2><p>{en?"EPCs, mine operators, OEMs and mineral dealers: connect equipment, sites and markets.":"EPC, exploitants miniers, OEM et négociants : connectez les équipements, les sites et les marchés."}</p></div><button className="outline-btn" onClick={()=>k.requestAI(en?"Explain Africa Global Logistics’s mining expertise using this screen.":"Explique-moi l’expertise Mining d’Africa Global Logistics à partir de cet écran.")}><Bot size={20}/>Lara</button></div>
    <div className="stage-tabs"><button className={mode==="lifecycle"?"active":""} onClick={()=>setMode("lifecycle")}>{en?"Mining lifecycle":"Cycle minier"}</button><button className={mode==="case"?"active":""} onClick={()=>setMode("case")}>{en?"Tokadeh case":"Cas Tokadeh"}</button><button className={mode==="quiz"?"active":""} onClick={()=>setMode("quiz")}>{en?"Take the challenge":"Relever le défi"}</button></div>
    {mode==="lifecycle"&&<><div className="stage-tabs">{MINING_STAGES.map((p,i)=>{const Icon=ICONS[i];return <button key={p.id} className={stage===i?"active":""} onClick={()=>setStage(i)}><Icon size={18}/>{en?p.en:p.fr}</button>;})}</div><motion.div key={s.id} initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="mining-layout"><div className="mining-stage-image"><img src={`/assets/template/${s.image}.webp`} alt={en?s.en:s.fr}/></div><div className="panel"><span className="eyebrow">0{stage+1} / 05 · {en?s.en:s.fr}</span><h3 style={{fontSize:32,marginTop:14}}>{en?s.titleEn:s.title}</h3><p style={{color:"#cbd8e9",lineHeight:1.7,marginBottom:22}}>{en?s.textEn:s.text}</p><div className="pill-row">{s.capabilities.map(c=><span className="pill" key={c}>{c}</span>)}</div><div className="button-row"><button className="brand-btn" onClick={()=>stage<4?setStage(stage+1):setMode("case")}>{stage<4?(en?"Next stage":"Étape suivante"):(en?"Discover Tokadeh":"Découvrir Tokadeh")}<ArrowRight size={18}/></button></div></div></motion.div><div className="panel" style={{marginTop:24}}><div className="pill-row"><span className="pill">QHSE & conformité</span><span className="pill">OOG & heavy lift</span><span className="pill">Hubs interconnectés</span><span className="pill">Track & trace / EDI / API</span><span className="pill">Local content</span></div><p style={{fontSize:12,color:"#aabbd2",marginTop:14}}>{en?"Capabilities drawn from the Mining presentation supplied for the stand. Local service availability must be confirmed with Africa Global Logistics.":"Expertises issues de la présentation Mining fournie pour le stand. La disponibilité locale des services est à confirmer avec Africa Global Logistics."}</p></div></>}
    {mode==="case"&&<><div className="mining-layout"><div className="panel"><span className="eyebrow">LIBERIA · RÉFÉRENCE PROJET</span><h3 style={{fontSize:32,marginTop:12}}>{TOKADEH.title}</h3><p style={{color:"#cbd8e9",lineHeight:1.7}}>{TOKADEH.context}</p><div className="metric-grid" style={{gridTemplateColumns:"1fr 1fr",marginTop:24,marginBottom:0}}><div><strong>34</strong><small>{en?"charter vessels discharged":"navires affrétés déchargés"}</small></div><div><strong>OOG</strong><small>{en?"specialised cargo":"cargaisons hors gabarit"}</small></div></div></div><div className="mining-stage-image"><img src="/assets/template/image26.webp" alt="Opérations portuaires Africa Global Logistics"/><span className="eyebrow" style={{position:"absolute",bottom:18,left:22,zIndex:1}}>VISUEL MÉTIER AFRICA GLOBAL LOGISTICS · ILLUSTRATION</span></div></div><div className="case-layout">{[["LES DÉFIS",TOKADEH.challenges],["LA RÉPONSE AFRICA GLOBAL LOGISTICS",TOKADEH.solutions]].map(([title,items])=><div className="panel" key={title as string}><h3>{title}</h3><ul className="case-list">{(items as string[]).map(item=><li key={item}><CheckCircle2 size={18}/>{item}</li>)}</ul></div>)}</div><div className="button-row"><button className="brand-btn" onClick={()=>setMode("quiz")}><Pickaxe size={20}/>{en?"Take the mining challenge":"Relever le défi Mining"}</button><button className="outline-btn" onClick={()=>downloadFile("Africa Global Logistics-Mining-Tokadeh.txt",`${TOKADEH.title}\n\n${TOKADEH.context}\n\nDÉFIS\n${TOKADEH.challenges.join("\n")}\n\nSOLUTIONS\n${TOKADEH.solutions.join("\n")}\n\nSource : ${TOKADEH.source}`)}><Download size={20}/>{en?"Download case summary":"Télécharger la fiche projet"}</button></div></>}
    {mode==="quiz"&&<div className="panel" style={{maxWidth:880,margin:"auto"}}><span className="eyebrow">DÉFI MINING · {q+1}/3 · {score} POINTS</span><h3 style={{fontSize:28,marginTop:16}}>{en?Q.qEn:Q.q}</h3><div className="quiz-options">{(en?Q.choicesEn:Q.choices).map((c,i)=><button className={answer!==null&&i===Q.correct?"correct":""} disabled={answer!==null} key={c} onClick={()=>{setAnswer(i);if(i===Q.correct)setScore(score+1);}}>{String.fromCharCode(65+i)} · {c}</button>)}</div>{answer!==null&&<><div className="quiz-feedback"><strong>{answer===Q.correct?(en?"Well done. ":"Bien joué. "):(en?"Here is the key insight. ":"Voici le point clé. ")}</strong>{en?Q.whyEn:Q.why}</div><div className="button-row"><button className="brand-btn" onClick={()=>q<2?(setQ(q+1),setAnswer(null)):finish()}>{q<2?(en?"Next question":"Question suivante"):(en?"Finish & share feedback":"Terminer & donner mon avis")}<ArrowRight size={18}/></button></div></>}</div>}
    {mode!=="quiz"&&<div className="button-row"><button className="outline-btn" onClick={()=>{k.setFinaleStats({Expérience:"Mining",Étape:s.fr});k.go("satisfaction");}}>{en?"Finish the experience":"Terminer l’expérience"}<ArrowRight size={18}/></button><button className="text-action" onClick={()=>k.go("appointment")}>{en?"Discuss my mining project":"Échanger sur mon projet minier"} →</button></div>}
  </main></div>;
}
